# Generated by Django 6.0.3 on 2026-03-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gioco',
            name='genere',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
