# Generated by Django 6.0.3 on 2026-03-30 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoteca', '0002_gioco_genere'),
    ]

    operations = [
        migrations.AddField(
            model_name='gioco',
            name='recensione',
            field=models.TextField(blank=True, null=True),
        ),
    ]
